<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Shared\Shared.MessageStore\Shared.MessageStore.csproj" />
		<ProjectReference Include="..\Repositories\Repositories.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Messaging.EventHubs" Version="5.12.1" />
		<PackageReference Include="DynamicExpresso.Core" Version="2.19.2" />
		<PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
		<PackageReference Include="MassTransit.Kafka" Version="8.4.0" />
		<PackageReference Include="AutoMapper" Version="14.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.0" />
		<PackageReference Include="Microsoft.Azure.Devices" Version="1.40.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
		<PackageReference Include="StackExchange.Redis" Version="2.8.41" />
		<PackageReference Include="VNPAY.NET" Version="8.5.0" />

	</ItemGroup>
	<ItemGroup>
		<None Update="Services/Background/workflow_seq.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
		<None Update="..\DataStorage\**\*.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
</Project>
