export const Path = {
    DASHBOARD: "/dashboard",
    MANAGE_ORDERS: "/manage-orders",
    MANAGE_DEVICES: "/manage-devices",
    MANAGE_KIOSKS: "/manage-kiosks",
    MANAGE_PRODUCTS: "/manage-products",
    MANAGE_WORKFLOWS: "/manage-workflows",
    MANAGE_MENUS: "/manage-menus",
    MANAGE_ORGANIZATIONS: "/manage-organizations",
    MANAGE_STORES: "/manage-stores",
    PROFILE: "/profile",
    REMINDER: "/reminder",
    NOT_FOUND: "/not-found",
    HOME: "/",
    LOGIN: "/login",
    MENUS_DETAIL: "/manage-menus/:slug",
    MANAGE_LOCATION_TYPES: "/manage-location-types",
    MANAGE_DEVICE_TYPES: "/manage-device-types",
    MANAGE_DEVICE_MODELS: "/manage-device-models",
    MANAGE_KIOSK_VERSIONS: "/manage-kiosk-versions",
    MANAGE_KIOSK_TYPES: "/manage-kiosk-types",
    CREATE_ACCOUNT: "/create-account",
    CREATE_WORKFLOW: "/create-workflow",
    UPDATE_WORKFLOW: "/update-workflow",
    MANAGE_ACCOUNTS: "/manage-accounts",
    MANAGE_SYNC_EVENT: "/manage-sync-events",
    MANAGE_SYNC_TASKS: "/manage-sync-tasks",
    INVALID_REQUEST: "/invalid-request",
    MANAGE_CATEGORIES: "/manage-categories",
    MANAGE_INGREDIENT_TYPE: "/manage-ingredient-types",
    MANAGE_NOTIFICATIONS: "/manage-notifications",
};

