<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
	  <PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.42.3" />
	  <PackageReference Include="dotenv.net" Version="3.2.1" />
    <ProjectReference Include="..\..\Shared\SerialDeviceConnector\SerialDeviceConnector.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.RabbitMqPublisher\Shared.RabbitMqPublisher.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.MessageStore\Shared.MessageStore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update=".env">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
